openapi: 3.0.4
info:
  title: Hjelpemidler API
  description: Select server that corresponds to the environment you want to use.
  version: 1.0.0
servers:
  - url: 'https://hjelpemidler-api.intern.dev.nav.no/api/v1'
    description: test environment
  - url: 'http://localhost:8080/api/v1'
    description: local environment
  - url: 'https://hjelpemidler-api.intern.nav.no/api/v1'
    description: production environment

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    brukernummer:
      type: string
      pattern: '^[0-9]+$'
      description: Brukernummer for the user
    fodselsnummer:
      type: string
      pattern: '^[0-9]{11}$'
      description: Fødselsnummer (11 siffer)
    status:
      type: boolean
      description: Indicates whether the user is active or not
    adresse:
      type: object
      properties:
        gateadresse:
          type: string
        postnummer:
          type: string
        by:
          type: string
        kommune:
          type: string
        bydel:
          type: string
          nullable: true
    brukerpass:
      type: object
      properties:
        kontraktnr:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    artikkel:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        beskrivelse:
          type: string


    bruker:
      type: object
      properties:
        brukernummer:
          $ref: '#/components/schemas/brukernummer'
        fodselsnummer:
          $ref: '#/components/schemas/fodselsnummer'
        status:
          $ref: '#/components/schemas/status'
        adresse:
          $ref: '#/components/schemas/adresse'
        leveringsadresse:
          $ref: '#/components/schemas/adresse'
        #Diverse statuser og primæradresse? Hvorfor skal det med?

paths:
  /bruker/{fnr}:
    get:
      operationId: getBruker
      summary: Get segments by segmentType and optionally filter by lastUpdateDate
      security:
        - BearerAuth: []
      parameters:
        - name: fnr
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/fodselsnummer'
      responses:
        '200':
          description: Bruker get for a given fødselsnummer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bruker'
              example: "test"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
  /bruker/brukernummer/{fnr}:
    get:
      operationId: getBrukernummer
      security:
        - BearerAuth: []
      summary: Get brukernummer for a given fødselsnummer
      parameters:
        - name: fnr
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/fodselsnummer'
      responses:
        '200':
          description: List of all segments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/brukernummer"
              example:
                "brukernummer": "123456789"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
  /bruker/fodselsnummer/{brukernummer}:
    get:
      operationId: getFodselsnummer
      security:
        - BearerAuth: []
      summary: Get fodselsnummer for a given brukernummer
      parameters:
        - name: brukernummer
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/brukernummer'
      responses:
        '200':
          description: Fodselsnummer for given brukernummer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fodselsnummer"
              example:
                "brukernummer": "123456789"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
  /bruker/brukerpass/{fnr}:
    get:
      operationId: getBrukerPass
      security:
        - BearerAuth: []
      summary: Get brukerpass for a given fodselsnummer
      parameters:
        - name: fnr
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/fodselsnummer'
      responses:
        '200':
          description: Brukerpass for å given fodselsnummer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/brukerpass"
              example:
                "example": "testexample"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
  /artikkel:
    get:
      operationId: getArtikler
      security:
        - BearerAuth: []
      summary: Get all artikler
      responses:
        '200':
          description: List of all artikler
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/artikkel'
              example:
                - id: "1"
                  type: "type1"
                  beskrivelse: "Beskrivelse av artikkel 1"
                - id: "2"
                  type: "type2"
                  beskrivelse: "Beskrivelse av artikkel 2"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
  /artikkel/{id}:
    get:
      operationId: getArtikkel
      security:
        - BearerAuth: []
      summary: Get artikkel for a given id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Artikkel for given id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/artikkel"
              example:
                "example": "testexample"
        '404':
          description: No segments found for the given segmentType
        '400':
          description: Invalid input parameters
        '500':
          description: Internal Server Error
